### ISSUE TITLE
Revisión final

### ISSUE THREAD

**Issue by LucianoEspe** [GMSanchezBattagion/Curso-Python#3]
Buenas Gonzalo, estuve revisando los códigos que no había visto.
El ejercicio del tamagotchi con el uso de hilos excelente, tuve un problemita cuando murió de tristeza, se quedó bloqueado el código, es por el bucle while dentro del hilo. Otro detallito son los límites mínimos y máximos en los atributos para no superarlos:
Energia:175
Hambre:-52
Felicidad:57
En ese caso el hambre tomó un valor negativo y la energía superó los 100 puntos.
Me faltó el ejercicio de la biblioteca, pero demostraste que sabes usar POO y archivos así que lo doy por entregado.
Genial el proyecto integrador, pude ver que pudiste empezar a definir razas, clases, excelente, si la completas espero ver la versión final.
Felicitaciones y saludos!

**Comment by GMSanchezBattagion** [comment]
Hola profe, ahi arreglé el ejercicio. Gracias por la devolucion.
